import { Link } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { ArrowLeft, Sprout } from 'lucide-react'

export function TermsOfService() {
  return (
    <div className="min-h-screen bg-background">
      <header className="flex items-center gap-4 px-6 py-4 max-w-3xl mx-auto">
        <Button variant="ghost" size="icon" asChild>
          <Link to="/"><ArrowLeft className="h-5 w-5" /></Link>
        </Button>
        <div className="flex items-center gap-2">
          <Sprout className="h-6 w-6 text-sage" />
          <span className="font-display text-lg font-semibold">Terms of Service</span>
        </div>
      </header>

      <main className="px-6 py-8 max-w-3xl mx-auto">
        <p className="text-xs text-terracotta font-medium mb-4">
          DRAFT — This document requires legal review before public use.
        </p>

        <div className="space-y-6">
          <section>
            <h2 className="font-display text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
            <p className="text-sm text-muted leading-relaxed">
              By creating an account on Seed, you agree to these Terms of Service and our Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-3">2. Eligibility</h2>
            <p className="text-sm text-muted leading-relaxed">
              You must be at least 18 years old and the parent or legal guardian of the children
              you add to Seed. Children do not create their own accounts.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-3">3. Service Description</h2>
            <p className="text-sm text-muted leading-relaxed">
              Seed provides personalized homeschool lesson plans and educational content generated
              using artificial intelligence. Content is designed to supplement, not replace, parental
              oversight of education.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-3">4. AI-Generated Content</h2>
            <p className="text-sm text-muted leading-relaxed">
              Lessons are generated by AI based on your child's profile and learning preferences.
              While we strive for accuracy and age-appropriateness, AI-generated content may
              occasionally contain errors. Parents are encouraged to review lessons and provide feedback.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-3">5. Subscription and Billing</h2>
            <p className="text-sm text-muted leading-relaxed">
              Free tier with limited features. Solo plan at $19/month and Family plan at $29/month.
              14-day free trial on paid plans. Cancel anytime.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl font-semibold mb-3">6. Limitation of Liability</h2>
            <p className="text-sm text-muted leading-relaxed">
              Seed is an educational tool, not a school. We do not guarantee that use of Seed meets
              your state's homeschool requirements. Parents are responsible for ensuring compliance
              with local education laws.
            </p>
          </section>
        </div>

        <p className="text-sm text-muted mt-8">
          Version 1.0 · Last updated: [Date to be set before launch]
        </p>
      </main>
    </div>
  )
}
